name: scf-images

on:
  push:
    branches: master

jobs:
  publish_image:
    name: Build Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["ubuntu", "alpine" ]
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      
      - name: "Build and push docker image"
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: ./Dockerfile.${{ matrix.platform }}
          tags: suilteam/base:${{ matrix.platform }}